spring:
  application:
    name: common
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB   # 최대 파일 크기
      max-request-size: 5MB  # 최대 요청 크기
  sms:
    api-key: ${SMS_API_KEY}
    api-secret: ${SMS_API_SECRET}
    provider: ${SMS_PROVIDER}
    sender: ${SMS_SENDER}
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${MAIL_USER} # SMTP 서버 로그인 아이디 (발신자)
    password: ${MAIL_PASSWORD} # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
openapi:
  service:
    title: common doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /common-swagger/v3/api-docs
  swagger-ui:
    path: /common-swagger/swagger-ui.html

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${COMMON_PORT}
  servlet:
    context-path: /api

config:
  clova:
    url: ${CLOVA_URL}
    secret: ${CLOVA_SECRET}


logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org:
      springframework:
        security: "trace"
#  file:
#    name: app/logs/application.log

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus, health, info
#  metrics:
#    tags:
#      application: auth-service