spring:
  application:
    name: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

openapi:
  service:
    title: common doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /common-swagger/v3/api-docs
  swagger-ui:
    path: /common-swagger/swagger-ui.html

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${COMMON_PORT}
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org:
      springframework:
        security: "trace"
#  file:
#    name: app/logs/application.log

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus, health, info
#  metrics:
#    tags:
#      application: auth-service