spring:
  application:
    name: gateway
  security:
    user:
      name: ${GATEWAY_USER}
      password: ${GATEWAY_PASSWORD}
  cloud:
    gateway:
      routes:
        - id: common
          uri: lb://common
          predicates:
            - Path=/common/**
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
        - id: card
          uri: lb://card
          predicates:
            - Path=/card/**
        - id: donation
          uri: lb://donation
          predicates:
            - Path=/donation/**
        - id: franchise
          uri: lb://franchise
          predicates:
            - Path=/franchise/**


eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${GATEWAY_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /member/v3/api-docs
        name: Member Service
      - url: /common/v3/api-docs
        name: Common Service
      - url: /card/v3/api-docs
        name: Card Service
      - url: /donation/v3/api-docs
        name: Donation Service
      - url: /franchise/v3/api-docs
        name: Franchise Service


logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
#  file:
#    name: app/logs/application.log