spring:
  application:
    name: gateway
#  security:
#    user:
#      name: ${GATEWAY_USER}
#      password: ${GATEWAY_PASSWORD}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'

            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            exposedHeaders:
              - 'Content-Disposition'
            allowCredentials: false

      routes:
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/auths/**
        - id: common-service
          uri: lb://common
          predicates:
            - Path=/commons/**
        - id: member-service
          uri: lb://member
          predicates:
            - Path=/members/**
        - id: card-service
          uri: lb://card
          predicates:
            - Path=/cards/**
        - id: donation-service
          uri: lb://donation
          predicates:
            - Path=/donations/**
        - id: franchise-service
          uri: lb://franchise
          predicates:
            - Path=/franchises/**


eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${GATEWAY_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /members/v3/api-docs
        name: Member Service

      - url: /auths/v3/api-docs
        name: Auth Service

      - url: /commons/v3/api-docs
        name: Common Service

      - url: /cards/v3/api-docs
        name: Card Service

      - url: /donations/v3/api-docs
        name: Donation Service

      - url: /franchises/v3/api-docs
        name: Franchise Service


logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
#  file:
#    name: app/logs/application.log