spring:
  application:
    name: gateway
  security:
    user:
      name: ${GATEWAY_USER}
      password: ${GATEWAY_PASSWORD}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'

            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            exposedHeaders:
              - 'Content-Disposition'
            allowCredentials: false

      routes:
        - id: auth-service
          uri: lb://auth
          predicates:
            - Path=/api/auths/**, /auths-swagger/**

        - id: common-service
          uri: lb://common
          predicates:
            - Path=/api/commons/**, /commons-swagger/**

        - id: member-service
          uri: lb://member
          predicates:
            - Path=/api/members/**, /members-swagger/**

        - id: card-service
          uri: lb://card
          predicates:
            - Path=/api/cards/**, /cards-swagger/**

        - id: donation-service
          uri: lb://donation
          predicates:
            - Path=/api/donations/**, /donations-swagger/**

        - id: franchise-service
          uri: lb://franchise
          predicates:
            - Path=/api/franchises/**, /franchises-swagger/**

        - id: payment-service
          uri: lb://payment
          predicates:
            - Path=/api/payments/**, /payments-swagger/**

        - id: funding-service
          uri: lb://funding
          predicates:
            - Path=/api/fundings/**, /fundings-swagger/**


eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${GATEWAY_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /members-swagger/v3/api-docs
        name: Member Service

      - url: /auths-swagger/v3/api-docs
        name: Auth Service

      - url: /commons-swagger/v3/api-docs
        name: Common Service

      - url: /cards-swagger/v3/api-docs
        name: Card Service

      - url: /donations-swagger/v3/api-docs
        name: Donation Service

      - url: /franchises-swagger/v3/api-docs
        name: Franchise Service

      - url: /payments-swagger/v3/api-docs
        name: Payment Service

      - url: /fundings-swagger/v3/api-docs
        name: Funding Service

jwt:
  issuer: ${JWT_ISSUER:defaultIssuer}
  secretKey: ${JWT_SECRET_KEY}


logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
#  file:
#    name: app/logs/application.log