spring:
  application:
    name: card
  datasource:
    driver-class-name:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${CARD_PORT}

