spring:
  application:
    name: donation

openapi:
  service:
    title: donation doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /donation/v3/api-docs
  swagger-ui:
    path: /donation/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/

server:
  port: ${DONATION_PORT}

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org:
      springframework:
        security: "trace"