spring:
  application:
    name: franchise

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: root
    url: jdbc:mysql://localhost:3306/franchise
    username: a601
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: update  # 또는 적절한 옵션 (create, create-drop, validate, none)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

openapi:
  service:
    title: franchise doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /franchise/v3/api-docs
  swagger-ui:
    path: /franchise/swagger-ui.html

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: true
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${FRANCHISE_PORT}

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org:
      springframework:
        security: "trace"