spring:
  application:
    name: funding

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  #create, create-drop, validate, none, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

openapi:
  service:
    title: funding doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /funding-swagger/v3/api-docs
  swagger-ui:
    path: /funding-swagger/swagger-ui.html

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: http://${BACKEND_SERVER}:${EUREKA_PORT}/eureka/


server:
  port: ${FUNDING_PORT}
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org:
      springframework:
        security: "trace"

config:
  kafka:
    KAFKA_SERVER: ${KAFKA_SERVER}
    KAFKA_PORT: ${KAFKA_PORT}
  fintech:
    api-key: ${FINTECH_API_KEY}
    institution-code: ${INSTITUTION_CODE}
    fintech-app-no: ${FINTECH_APP_NO}
    fintech-urI: ${FINTECH_URL}

    funding:
      user-key: ${FINTECH_MANAGER_USER_KEY}
      deposit-account-no: ${DEPOSIT_ACCOUNT_NO}
      withdrawal-account-no: ${WITHDRAWAL_ACCOUNT_NO}
